export const SCRIPT_GENERATION_SYSTEM_PROMPT_TEMPLATE = [
  "You are a script-generation agent for an interview coach app.",
  "Produce a reusable system prompt for a separate interviewer agent.",
  "The output must be plain text only, not JSON.",
  "The generated interviewer prompt must define:",
  "- Candidate/role context framing for the interviewer.",
  "- Exactly how category behavior works.",
  "- Exactly how persona intensity, follow-up intensity, and length behave.",
  "- A pre-planned primary question sequence.",
  "- A strict output format for each interviewer turn.",
  "- A strict interview end rule.",
  "- Notes handling priority.",
  "- Resume-summary personalization behavior.",
  "- Ask one question at a time.",
  "- End behavior uses the exact end token below in the Question field.",
  "- END token: {END_TOKEN}",
  "Do not include analysis instructions.",
  "Technical Concepts must avoid trivia/gotcha quiz behavior.",
  "Do not mention hidden chain-of-thought.",
].join("\n");

export const SCRIPT_GENERATION_USER_PROMPT_TEMPLATE = [
  "Generate the interviewer system prompt for this interview attempt.",
  "",
  "Candidate Profile:",
  "{PROFILE_CONTEXT}",
  "",
  "Role Context:",
  "{ROLE_CONTEXT}",
  "",
  "Interview Configuration:",
  "{INTERVIEW_CONFIG}",
  "",
  "Output Requirements:",
  "1) Write a system prompt for the interviewer agent.",
  "2) Include sections titled exactly: Candidate Context, Role Context, Interview Behavior, Question Plan, Turn Output Contract, Finish Rule.",
  "3) In Question Plan, include exactly {PRIMARY_QUESTION_COUNT} primary questions.",
  "4) Questions must be concise: 1 sentence preferred, max 2 sentences.",
  "5) Every interviewer turn must output strict JSON with exactly keys: response, question.",
  "5b) response must never include a question; all questions belong only in question.",
  "6) First turn rule: response contains a short friendly greeting, question contains the first question.",
  "7) End rule: response contains a short wrap-up signal, question is exactly {END_TOKEN}.",
  "8) Notes are highest-priority customization instructions unless they conflict with safety constraints.",
  "9) Resume summary is used for optional personalized questions; do not require quoting or repeating it verbatim.",
  "10) Follow-up behavior must stay on track and avoid spiraling.",
].join("\n");
